### ISSUE TITLE
Support for .net6.0 / Reasoning why .net7 is required

### ISSUE THREAD

**Issue by kirides** [christianhelle/refitter#17]
i don't quite get the reasoning why the LTS net6.0 is not supported.

i can't install this tool into our build, because we develop on "LTS"s only.
Current workaround is to install the tool globally if net7.0 is installed and use the global executable.

**Comment by christianhelle** [comment]
I have absolutely no reason for choosing .NET 7.0 as the target. I have nothing against lowering the target framework to .NET 6.0 as there is nothing really specific to .NET 7.0 that I'm using.

To be honest, the only reason I can think that this targets .NET 7.0 was because that's what I created the project with. At that time, I just made it for myself to solve my own problem
