### ISSUE TITLE
NSwag contracts

### ISSUE THREAD

**Issue by bielik01** [christianhelle/refitter#186]
Maybe it's there and I couldn't find it, but when generating contracts, I'd like to specify some NSwag options like dateType (I don't like DateTimeOffset) or arrayType.

**Comment by bielik01** [comment]
Yeah, there's a lot of default parameters in CSharpClientGeneratorFactory.

**Comment by christianhelle** [comment]
@bielik01 I actually have this in my backlog. I plan to expose settings to customize the entire [CSharpGeneratorSettings](https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpGeneratorSettings.cs)

You have things like these options that can be customized

```csharp
AnyType = "object";
Namespace = "MyNamespace";

DateType = "System.DateTimeOffset";
DateTimeType = "System.DateTimeOffset";
TimeType = "System.TimeSpan";
TimeSpanType = "System.TimeSpan";

ArrayType = "System.Collections.Generic.ICollection";
ArrayInstanceType = "System.Collections.ObjectModel.Collection";
ArrayBaseType = "System.Collections.ObjectModel.Collection";

DictionaryType = "System.Collections.Generic.IDictionary";
DictionaryInstanceType = "System.Collections.Generic.Dictionary";
DictionaryBaseType = "System.Collections.Generic.Dictionary";

ClassStyle = CSharpClassStyle.Poco;
JsonLibrary = CSharpJsonLibrary.NewtonsoftJson;

RequiredPropertiesMustBeDefined = true;
GenerateDataAnnotations = true;
TypeAccessModifier = "public";
PropertySetterAccessModifier = string.Empty;
GenerateJsonMethods = false;
EnforceFlagEnums = false;

InlineNamedArrays = false;
InlineNamedDictionaries = false;
InlineNamedTuples = true;
```

So the .refitter settings file might look something like:

```json
{
  "openApiPath": "./OpenAPI/v3.0/petstore.json",
  "namespace": "Petstore",
  "contractsGeneratorSettings": {
    "dateType": "System.DateTime",
    "dateTimeType": "System.DateTime",
    "arrayType": "System.Collections.Generic.IList"
  }
}
```

**Comment by christianhelle** [comment]
@all-contributors please add @bielik01 for ideas

**Comment by alrz** [comment]
Is it "contractsGeneratorSettings" or "codeGeneratorSettings"? In the README it's the former and neither of them works..

![image](https://github.com/christianhelle/refitter/assets/3105979/ae269efc-746a-4584-aa02-a196c7992ed5)


Also I just confused with "namespace" being mentioned at the top level AND the settings part. The former is valid.

**Comment by alrz** [comment]
Oh wait, I guess this is not yet reached nuget..

**Comment by christianhelle** [comment]
> Is it "contractsGeneratorSettings" or "codeGeneratorSettings"? In the README it's the latter.
> 
> 
> 
> Also I just confused with "namespace" being mentioned at the top level AND the settings part. The former is valid.

I went with codeGeneratorSettings as it's not only the types used in the contract/dto, it's also the arguments and return types in the Refit interface

**Comment by christianhelle** [comment]
> Also I just confused with "namespace" being mentioned at the top level AND the settings part. The former is valid.

This is a mistake and only the top level `namespace` is used. The codeGeneratorSettings was a copy of the NSwag type, and I was supposed to clean it up

Thanks for pointing that out @alrz

**Comment by christianhelle** [comment]
@all-contributors please add @alrz for bugs

**Comment by bielik01** [comment]
but that was namespace for contracts, it was perfectly fine there

**Comment by christianhelle** [comment]
> but that was namespace for contracts, it was perfectly fine there

@bielik01 Are you interested in having different namespaces for contracts and the interfaces? That's not how its currently implemented and I originally wanted to use the same namespace for all generated types, be it DTO objects or the interface(s), since they are in the same file. Having different namespaces for contracts and interfaces would require importing the contracts namespace into each interface, or specifying the full type name on all usages

I have toyed with the idea of splitting the contracts and interfaces into different files, but it's not how I personally use the tool, and I didn't want to assume how others might use it

Is there an interest for splitting the output into multiple files? It's not really that hard to implement, and I won't use it myself, but if there are others who need it then why not 😃

**Comment by bielik01** [comment]
`namespace` from `codeGeneratorSettings` worked for me with `additionalNamespaces`, but yeah, `output` (from `openApiToCSharpClient` in [NSwag Configuration Document](https://github.com/RicoSuter/NSwag/wiki/NSwag-Configuration-Document)) is missing to generate contracts separately from the interface, but I don't know how to place it...

and https://github.com/christianhelle/refitter/issues/184 is missing to completion 😅

**Comment by christianhelle** [comment]
> `namespace` from `codeGeneratorSettings` worked for me with `additionalNamespaces`, but yeah, `output` (from `openApiToCSharpClient` in [NSwag Configuration Document](https://github.com/RicoSuter/NSwag/wiki/NSwag-Configuration-Document)) is missing to generate contracts separately from the interface, but I don't know how to place it...

Currently, NSwag returns me a string containing all the generated contracts. I can write this to another file if we can introduce a setting that describes it. 

A lot of the options in `openApiToCSharpClient` are options for how NSwag will generate the API Client and they are irrelevant to Refitter since Refitter generates the Refit interface manually, only using NSwag to parse the OpenAPI spec


> and #184 is missing to completion 😅

Coming soon :)


> I wonder if it should stay `codeGeneratorSettings`, maybe `contractsGeneratorSettings` as you first envisioned it would be better, to indicate it's only for NSwag contracts

I renamed it to `codeGeneratorSettings` because these settings affect how the OpenAPI spec is parsed, which I use for generating the Refit interface. So if you specify the `dateTimeType` to be `System.DateTime` it also affects query string parameters, the same goes for `arrayType` which can be at times used as a return type to methods in the Refit interface

**Comment by christianhelle** [comment]
Not really much left for me to do here so I'll close this issue
