### ISSUE TITLE
Parameters from the query do not add into the resulting interface

### ISSUE THREAD

**Issue by 1kvin** [christianhelle/refitter#5]
https://github.com/christianhelle/refitter/blob/main/src/Refitter.Core/ParameterExtractor.cs#L15

I noticed that in the file ParameterExtractor.cs, parameters are added for the route and the body, but not for the query.

**Comment by christianhelle** [comment]
@1kvin Thanks for pointing this out!

I most likely missed this because the OpenAPI specifications that I have been working with for this project didn't use query parameters

I took the example specifications [from official OpenAPI Specifications github repo](https://github.com/christianhelle/refitter/commit/2dd5c01e37d356d861ab079e817bd37ee9c160ac) and started off with getting those to work

**Comment by christianhelle** [comment]
@1kvin I have implemented the changes so it now generates Query parameters like this:

```cs
[Get("/pet/findByStatus")]
Task<ICollection<Pet>> FindPetsByStatus([Query]Status? status);

[Get("/pet/findByTags")]
Task<ICollection<Pet>> FindPetsByTags([Query(CollectionFormat.Multi)]ICollection<string> tags);
```

**Comment by 1kvin** [comment]
Good job!
